@echo off
REM Stopping Apache server...
echo Stopping Apache server...
net stop Tomcat9
REM Waiting for 5 seconds for apache server to stop...
echo Waiting for 5 seconds
ping 192.0.2.2 -n 1 -w 5000 > nul
REM Stopping MySQL server...
echo Stopping MySQL server...
net stop MySQL80
echo Waiting for 5 seconds
ping 192.0.2.2 -n 1 -w 5000 > nul
REM Deploying war file to Apache server...
echo Deploying war file to Apache server
copy "C:\Program Files (x86)\Jenkins\workspace\(Deploy) - DEV - Employee Management\target\dependency\employee-management-${release}.war" "C:\Softwares\apache-tomcat-9.0.36-windows-x64\apache-tomcat-9.0.36\webapps\"
REM Starting Apache server...
echo Starting Apache server...
net start Tomcat9
echo Waiting for 5 seconds for Apache server to start
ping 192.0.2.2 -n 1 -w 5000 > nul
REM Starting MySQL server...
echo Starting MySQL server...
net start MySQL80
echo Waiting for 5 seconds for MySQL server to start
ping 192.0.2.2 -n 1 -w 5000 > nul
echo All servers started
exit 0