---
- hosts: master
  become: true

  tasks:
    - name: create tag to image
      command: docker pull 192.168.0.7:8083/tt2-${build_deploy}:1.0

    - name: docker login to nexus local repo
      command: docker login -u admin -p admin 192.168.0.7:8083

    - name: push image on to nexus local repo
      command: docker push 192.168.0.7:8083/tt2-{{BUILD_NUMBER}}:1.0

    - name: run docker container from docker image
      command: docker run -d -p{{HOST_PORT}}:8080 --name tt2-{{BUILD_NUMBER}} 192.168.0.7:8083/tt2-{{BUILD_NUMBER}}:1.0